//
// Created by mac on 4/30/16.
//

#ifndef FINALPROJECTBIOMED_CUSTOMIMAGEVIEWER_H
#define FINALPROJECTBIOMED_CUSTOMIMAGEVIEWER_H


class CustomImageViewer {

};


#endif //FINALPROJECTBIOMED_CUSTOMIMAGEVIEWER_H
